//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyDenominationTran
    {
        public int id { get; set; }
        public Nullable<int> denomival { get; set; }
        public Nullable<int> countavai { get; set; }
        public Nullable<long> denomitotal { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
