//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen
    {
        public Kitchen()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int KitchenID { get; set; }
        public string KitchenName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
