//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderedProducts = new HashSet<OrderedProduct>();
        }
    
        public long Id { get; set; }
        public long ProductGroupID { get; set; }
        public Nullable<long> MasterProductID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> LowStockRange { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> FirstSellingPrice { get; set; }
        public Nullable<decimal> SecondSellingPrice { get; set; }
        public Nullable<decimal> ThirdSellingPrice { get; set; }
        public Nullable<decimal> FourthSellingPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsQuickProduct { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<OrderedProduct> OrderedProducts { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
