//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> Bills { get; set; }
        public DbSet<CurrencyDenomination> CurrencyDenominations { get; set; }
        public DbSet<CurrencyDenominationTran> CurrencyDenominationTrans { get; set; }
        public DbSet<Kitchen> Kitchens { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<OldBill> OldBills { get; set; }
        public DbSet<OldCurrencyDenominationTran> OldCurrencyDenominationTrans { get; set; }
        public DbSet<OldOrder> OldOrders { get; set; }
        public DbSet<OldOrderedProduct> OldOrderedProducts { get; set; }
        public DbSet<OldRePrint> OldRePrints { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderedProduct> OrderedProducts { get; set; }
        public DbSet<Printer> Printers { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductGroup> ProductGroups { get; set; }
        public DbSet<RePrint> RePrints { get; set; }
    
        public virtual int usp_MoveToOld()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MoveToOld");
        }
    }
}
